replicaCount: 1
image:
  repository: harbor.local/library/react-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: harbor-credentials

labels:
  app: frontend

selectorLabels:
  app: frontend


service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "320Mi"

nginxConfiguration:
  backendHost: backend
  backendPort: 8081
