FROM node:22.9.0-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:stable-alpine


COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /var/www/frontend

EXPOSE 80
EXPOSE 443
