replicaCount: 1
image:
  repository: harbor.local/library/java-backend
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: harbor-credentials

service:
  type: ClusterIP
  port: 8081

labels:
  app: backend

selectorLabels:
  app: backend

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "320Mi"

env:
  POSTGRES_HOST: postgres-postgresql.postgres.svc.cluster.local
  POSTGRES_PORT: 5432
  POSTGRES_USER: java_user
  POSTGRES_DB: java_db

  REDIS_HOST: redis-master.redis.svc.cluster.local
  REDIS_PORT: 6379

  FLUENTD_ENABLED: true
  FLUENTD_HOST: fluentd.logging.svc.cluster.local
  FLUENTD_PORT: 24224

  SERVER_PORT: 8081
  DEBUG: true

secret:
  POSTGRES_PASSWORD: qwezxc123
