name: Build Images

on:
  push:
    branches: [ main ]

jobs:
  build-back:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Kaniko build backend
        uses: aevea/action-kaniko@master
        with:
          registry: gitlab:5050
          image: root/test/java-backend
          username: ${{ secrets.GITLAB_REGISTRY_USER }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
          tag: ${{ github.sha }}
          path: back-end
          build_file: dockerfile
          extra_args: "--insecure --skip-tls-verify --ignore-path=/product_uuid"
#asdf
  build-front:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Kaniko build frontend
        uses: aevea/action-kaniko@master
        with:
          registry: gitlab:5050
          image: root/test/react-frontend
          username: ${{ secrets.GITLAB_REGISTRY_USER }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
          tag: ${{ github.sha }}
          path: front-end
          build_file: dockerfile
          extra_args: "--insecure --skip-tls-verify --ignore-path=/product_uuid"

  deploy:
    needs: [build-back, build-front]
    runs-on: self-hosted
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Check access
        run: |
          kubectl get ns
          helm list -A
  
      - name: Deploy backend
        run: |
  
          helm upgrade --install backend ./charts/backend \
            --namespace default \
            --set image.repository=gitlab:5050/root/test/java-backend \
            --set image.tag=${{ github.sha }}
  
      - name: Deploy frontend
        run: |
  
          helm upgrade --install frontend ./charts/frontend \
            --namespace default \
            --set image.repository=gitlab:5050/root/test/react-frontend \
            --set image.tag=${{ github.sha }}
