name: Build and Deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: gitlab:5050
  BACK_IMAGE: gitlab:5050/root/test/java-backend
  FRONT_IMAGE: gitlab:5050/root/test/react-frontend
  TAG: ${{ github.sha }}

jobs:

  build-back:
    runs-on: self-hosted

    container:
      image: gcr.io/kaniko-project/executor:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build backend
        run: |
          /kaniko/executor \
            --context=./back-end \
            --dockerfile=./back-end/Dockerfile \
            --destination=${BACK_IMAGE}:${TAG} \
            --insecure \
            --skip-tls-verify \
            --cache=true \
            --cleanup

  build-front:
    runs-on: self-hosted
    container:
      image: gcr.io/kaniko-project/executor:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build frontend
        run: |
          /kaniko/executor \
            --context=./front-end \
            --dockerfile=./front-end/Dockerfile \
            --destination=${FRONT_IMAGE}:${TAG} \
            --insecure \
            --skip-tls-verify \
            --cache=true \
            --cleanup

  deploy:
    needs: [build-back, build-front]
    runs-on: self-hosted

    container:
      image: alpine/helm:3.12.0

    steps:
      - uses: actions/checkout@v4

      - name: Deploy helm
        run: |
          helm upgrade --install app ./charts/app \
            --namespace default \
            --set backend.image=${BACK_IMAGE}:${TAG} \
            --set frontend.image=${FRONT_IMAGE}:${TAG}
